# Generated by Django 2.2.4 on 2020-11-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quniaodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(max_length=5)),
                ('month', models.TextField(max_length=5)),
                ('day', models.TextField(max_length=5)),
                ('hour', models.TextField(max_length=5)),
                ('min', models.TextField(max_length=5)),
            ],
        ),
    ]
