# Generated by Django 2.2.4 on 2020-11-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quniaodata',
            name='day',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quniaodata',
            name='hour',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quniaodata',
            name='min',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quniaodata',
            name='month',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='quniaodata',
            name='year',
            field=models.IntegerField(),
        ),
    ]
