# Generated by Django 2.2.4 on 2020-11-02 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201102_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='quniaodata',
            name='time',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
