# Generated by Django 2.2.4 on 2020-11-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_quniaodata_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='quniao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
    ]
